/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        'turma-yellow': '#FFB700',
        'turma-yellow-light': '#FFC94D',
        'turma-yellow-dark': '#E5A500',
        'turma-green': '#1E7E34',
        'turma-green-light': '#2A9A44',
        'turma-green-dark': '#156226',
        'primary': '#1e7e34',
        'primary-container': '#1e7e34',
        'secondary': '#825500',
        'secondary-container': '#ffae1a',
        'tertiary': '#56572e',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-background': '#1a1c19',
        'on-surface': '#1a1c19',
        'on-surface-variant': '#3f493e',
        'surface': '#fafaf5',
        'surface-container': '#eeeee9',
        'surface-container-low': '#f4f4ef',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e8e8e4',
        'surface-dim': '#dadad6',
        'surface-bright': '#fafaf5',
        'outline': '#6f7a6d',
        'outline-variant': '#bfcaba',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        'card': '1.5rem',
      },
    },
  },
  plugins: [],
}